project:
  name: "web app example"
  version: "0.2.0"
  debug: true
  environment: "development"
log:
  level: "debug"
  output_format: "text"
  write_to_file: false
  path: "var/log/app.log"
server:
  host: ""
  port: 8080
  read_header_timeout: 5s
  write_timeout: 30s
  idle_timeout: 30s
handler:
  templates_dir: "templates"
  template_name: "default"
